sudo: required
language: r

services:
  - docker

addons:
  apt:
    packages:
    - postgresql-client

env:
  matrix:
    - BUILD_CONTAINER=True
    - TEST_FUNCTIONALITY=True
  global:
    - dbConnection='postgresql://scxa:postgresPass@localhost/scxa-test'

matrix:
  allow_failures:
    - env: BUILD_CONTAINER=True

before_install:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        sudo /etc/init.d/postgresql stop
        docker run -e POSTGRES_PASSWORD=postgresPass -e POSTGRES_USER=scxa -e POSTGRES_DB=scxa-test -p 5432:5432 -d postgres:10.3-alpine
    fi

install:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        Rscript -e "install.packages(c('optparse', 'tidyr'));"
    fi
  - ls

script:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        sleep 10 # lets give time for postgres to start
        bash tests/run_tests.sh
    fi
  - |
    if [ "${BUILD_CONTAINER}" ]
    then
        docker build -t test/db-scxa-module .
    fi
  - ls
