sudo: required
language: python
python: 3.6

services:
  - docker

addons:
  apt:
    packages:
    - postgresql-client

env:
  matrix:
    - BUILD_CONTAINER=True
    - TEST_FUNCTIONALITY=True
  global:
    - dbConnection='postgresql://scxa:postgresPass@localhost/scxa-test'

before_install:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        sudo /etc/init.d/postgresql stop
        docker run -e POSTGRES_PASSWORD=postgresPass -e POSTGRES_USER=scxa -e POSTGRES_DB=scxa-test -p 5432:5432 -d postgres:10.3-alpine
    fi

install:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        bash miniconda.sh -b -p $HOME/miniconda
        export PATH="$HOME/miniconda/bin:$PATH"
        hash -r
        conda config --set always_yes yes --set changeps1 no
        conda update -q conda
        conda info -a
        conda config --add channels conda-forge
        conda config --add channels bioconda
        conda install -n root _license
        conda install r-base r-tidyr r-optparse
    fi
  - ls

script:
  - set -e
  - |
    if [ "${TEST_FUNCTIONALITY}" ]
    then
        export PATH="$HOME/miniconda/bin:$PATH"
        sleep 10 # lets give time for postgres to start
        bash tests/run_tests.sh
    fi
  - |
    if [ "${BUILD_CONTAINER}" ]
    then
        docker build -t test/db-scxa-module .
    fi
  - ls
