sudo: required
language: r

services:
  - docker

addons:
  apt:
    packages:
    - postgresql-client


before_install:
  - sudo /etc/init.d/postgresql stop
  - docker run -e POSTGRES_PASSWORD=postgresPass -e POSTGRES_USER=scxa -e POSTGRES_DB=scxa-test -p 5432:5432 -d postgres:10.3-alpine

env:
  - dbConnection='postgresql://scxa:postgresPass@localhost/scxa-test'

install:
  - Rscript -e "install.packages(c('optparse', 'tidyr'));"

script:
  - sleep 10 # lets give time for postgres to start
  - bash tests/run_tests.sh
