sudo: required

services:
  - docker

before_install:
  - docker run -e POSTGRES_PASSWORD=postgresPass -e POSTGRES_USER=scxa -e POSTGRES_DB=scxa-test -p 5432:5432 -d postgres:10.3-alpine

addons:
  apt:
    packages:
    - r-base
    - postgresql-client
    - r-cran-optparse

env:
  - dbConnection='postgresql://scxa:postgresPass@localhost/scxa-test'

script:
  - sleep 15 # lets give time for postgres to start
  - bash tests/run_tests.sh
